#!/usr/bin/env python3
"""Convert Flappy Bird CC0 PNGs/WAVs under assets/flappy into LVGL C arrays.

Outputs (written next to this script's --out-dir):
  flappy_img.c / flappy_img.h   — RGB565A8 sprites
  flappy_sfx.c / flappy_sfx.h   — raw WAV blobs + play stub declarations

Sky is intentionally NOT a full-screen RGBA image (flash/RAM); the app keeps
a solid color sampled from Kenney background.png.
"""
from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

from PIL import Image

# Target sizes for classic layout on 240x284.
BIRD_W, BIRD_H = 34, 28  # ~88x73 aspect
PIPE_W, PIPE_H = 52, 115  # scaled from 108x239
GROUND_TILE_W, GROUND_H = 48, 71  # Kenney ground height; tile width


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def to_rgb565a8(im: Image.Image) -> tuple[bytes, int, int]:
    im = im.convert("RGBA")
    w, h = im.size
    px = im.load()
    color = bytearray()
    alpha = bytearray()
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            # Chroma-key near-white fringe left by palette upsample
            if a < 16:
                color += struct.pack("<H", 0)
                alpha.append(0)
            else:
                color += struct.pack("<H", rgb565(r, g, b))
                alpha.append(a)
    return bytes(color) + bytes(alpha), w, h


def c_array(name: str, data: bytes, per_line: int = 12) -> str:
    lines = []
    for i in range(0, len(data), per_line):
        chunk = data[i : i + per_line]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    return (
        f"const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST "
        f"uint8_t {name}[{len(data)}] = {{\n"
        + "\n".join(lines)
        + "\n};\n"
    )


def img_dsc(var: str, map_name: str, w: int, h: int, data_len: int) -> str:
    return f"""const lv_image_dsc_t {var} = {{
    .header = {{
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .flags = 0,
        .w = {w},
        .h = {h},
        .stride = {w * 2},
        .reserved_2 = 0,
    }},
    .data_size = {data_len},
    .data = {map_name},
    .reserved = NULL,
}};
"""


def sample_sky(bg_path: Path) -> tuple[int, int, int]:
    im = Image.open(bg_path).convert("RGB")
    # Average a horizontal strip near the top (sky).
    crop = im.crop((0, 0, im.width, max(1, im.height // 5)))
    pixels = list(crop.getdata())
    n = len(pixels)
    r = sum(p[0] for p in pixels) // n
    g = sum(p[1] for p in pixels) // n
    b = sum(p[2] for p in pixels) // n
    return r, g, b


def prepare_bird(src: Path) -> Image.Image:
    im = Image.open(src).convert("RGBA")
    return im.resize((BIRD_W, BIRD_H), Image.Resampling.LANCZOS)


def prepare_pipe(src: Path) -> Image.Image:
    im = Image.open(src).convert("RGBA")
    return im.resize((PIPE_W, PIPE_H), Image.Resampling.LANCZOS)


def prepare_ground(src: Path) -> Image.Image:
    im = Image.open(src).convert("RGBA")
    # Kenney ground is 808x71; take a tileable slice near the left.
    tile = im.crop((0, 0, GROUND_TILE_W, GROUND_H))
    return tile


def emit_images(png_dir: Path, out_dir: Path, sky: tuple[int, int, int]) -> None:
    assets = []

    for i, name in enumerate(("planeYellow1.png", "planeYellow2.png", "planeYellow3.png"), 1):
        data, w, h = to_rgb565a8(prepare_bird(png_dir / name))
        assets.append((f"flappy_bird_{i}", data, w, h))

    data, w, h = to_rgb565a8(prepare_pipe(png_dir / "rockGrassDown.png"))
    assets.append(("flappy_pipe_top", data, w, h))

    data, w, h = to_rgb565a8(prepare_pipe(png_dir / "rockGrass.png"))
    assets.append(("flappy_pipe_bot", data, w, h))

    data, w, h = to_rgb565a8(prepare_ground(png_dir / "groundGrass.png"))
    assets.append(("flappy_ground", data, w, h))

    h_path = out_dir / "flappy_img.h"
    c_path = out_dir / "flappy_img.c"

    h_path.write_text(
        "/* Auto-generated by scripts/flappy_assets_to_c.py — do not edit. */\n"
        "#pragma once\n\n"
        "#include \"lvgl.h\"\n\n"
        f"/* Sky fill sampled from Kenney background.png (not a full-screen bitmap). */\n"
        f"#define FLAPPY_SKY_R {sky[0]}\n"
        f"#define FLAPPY_SKY_G {sky[1]}\n"
        f"#define FLAPPY_SKY_B {sky[2]}\n\n"
        f"#define FLAPPY_BIRD_W {BIRD_W}\n"
        f"#define FLAPPY_BIRD_H {BIRD_H}\n"
        f"#define FLAPPY_PIPE_W {PIPE_W}\n"
        f"#define FLAPPY_PIPE_H {PIPE_H}\n"
        f"#define FLAPPY_GROUND_TILE_W {GROUND_TILE_W}\n"
        f"#define FLAPPY_GROUND_H {GROUND_H}\n\n"
        + "".join(f"extern const lv_image_dsc_t {n};\n" for n, *_ in assets)
        + "\n"
    )

    parts = [
        "/* Auto-generated by scripts/flappy_assets_to_c.py — do not edit. */\n",
        '#include "flappy_img.h"\n\n',
    ]
    for name, data, w, h in assets:
        map_name = f"{name}_map"
        parts.append(c_array(map_name, data))
        parts.append("\n")
        parts.append(img_dsc(name, map_name, w, h, len(data)))
        parts.append("\n")
    c_path.write_text("".join(parts))
    print(f"wrote {h_path} and {c_path} ({len(assets)} images)")


def emit_sfx(sfx_dir: Path, out_dir: Path) -> None:
    files = [
        ("flappy_sfx_flap", "phaseJump1.wav"),
        ("flappy_sfx_score", "powerUp2.wav"),
        ("flappy_sfx_die", "lowDown.wav"),
    ]
    blobs = []
    for var, fname in files:
        data = (sfx_dir / fname).read_bytes()
        blobs.append((var, fname, data))

    h_path = out_dir / "flappy_sfx.h"
    c_path = out_dir / "flappy_sfx.c"

    h_path.write_text(
        "/* Auto-generated by scripts/flappy_assets_to_c.py — do not edit. */\n"
        "#pragma once\n\n"
        "#include <stddef.h>\n"
        "#include <stdint.h>\n\n"
        "typedef enum {\n"
        "    FLAPPY_SFX_FLAP = 0,\n"
        "    FLAPPY_SFX_SCORE,\n"
        "    FLAPPY_SFX_DIE,\n"
        "} flappy_sfx_id_t;\n\n"
        "typedef struct {\n"
        "    const uint8_t *data;\n"
        "    size_t len;\n"
        "    const char *name;\n"
        "} flappy_sfx_blob_t;\n\n"
        + "".join(
            f"extern const uint8_t {var}[{len(data)}];\n"
            f"#define {var.upper()}_LEN {len(data)}\n"
            for var, _, data in blobs
        )
        + "\nextern const flappy_sfx_blob_t flappy_sfx_table[3];\n\n"
        "/* Minimal play hook. No ES8311 / I2S path in firmware yet (audio is\n"
        " * Planeado). Logs at DEBUG and returns ESP_ERR_NOT_SUPPORTED until\n"
        " * a real codec player exists. */\n"
        "void flappy_sfx_play(flappy_sfx_id_t id);\n"
    )

    parts = [
        "/* Auto-generated by scripts/flappy_assets_to_c.py — do not edit. */\n",
        '#include "flappy_sfx.h"\n\n',
        '#include "esp_log.h"\n\n',
        'static const char *TAG = "flappy_sfx";\n\n',
    ]
    for var, fname, data in blobs:
        parts.append(f"/* Source: assets/flappy/sfx/{fname} (16 kHz mono PCM WAV) */\n")
        parts.append(c_array(var, data))
        parts.append("\n")

    parts.append("const flappy_sfx_blob_t flappy_sfx_table[3] = {\n")
    for var, fname, data in blobs:
        parts.append(
            f'    {{ {var}, sizeof({var}), "{fname}" }},\n'
        )
    parts.append("};\n\n")
    parts.append(
        "void flappy_sfx_play(flappy_sfx_id_t id)\n"
        "{\n"
        "    if ((int)id < 0 || (int)id >= 3) {\n"
        "        return;\n"
        "    }\n"
        "    const flappy_sfx_blob_t *b = &flappy_sfx_table[id];\n"
        "    /* TODO(audio): feed b->data into ES8311 / esp_codec_dev when the\n"
        "     * board audio path is brought up. Assets are already 16 kHz mono WAV. */\n"
        '    ESP_LOGD(TAG, "play %s (%u bytes) — audio path not wired",\n'
        "             b->name, (unsigned)b->len);\n"
        "    (void)b;\n"
        "}\n"
    )
    c_path.write_text("".join(parts))
    print(f"wrote {h_path} and {c_path} ({len(blobs)} sfx)")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--assets",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "assets" / "flappy",
    )
    ap.add_argument(
        "--out-dir",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "main",
    )
    args = ap.parse_args()
    png_dir = args.assets / "png"
    sfx_dir = args.assets / "sfx"
    args.out_dir.mkdir(parents=True, exist_ok=True)
    sky = sample_sky(png_dir / "background.png")
    print(f"sky RGB = {sky}")
    emit_images(png_dir, args.out_dir, sky)
    emit_sfx(sfx_dir, args.out_dir)
    return 0


if __name__ == "__main__":
    sys.exit(main())
