/* Auto-generated by scripts/flappy_assets_to_c.py — do not edit. */
#pragma once

#include "lvgl.h"

/* Sky fill sampled from Kenney background.png (not a full-screen bitmap). */
#define FLAPPY_SKY_R 213
#define FLAPPY_SKY_G 236
#define FLAPPY_SKY_B 246

#define FLAPPY_BIRD_W 34
#define FLAPPY_BIRD_H 28
#define FLAPPY_PIPE_W 52
#define FLAPPY_PIPE_H 115
#define FLAPPY_GROUND_TILE_W 48
#define FLAPPY_GROUND_H 71

extern const lv_image_dsc_t flappy_bird_1;
extern const lv_image_dsc_t flappy_bird_2;
extern const lv_image_dsc_t flappy_bird_3;
extern const lv_image_dsc_t flappy_pipe_top;
extern const lv_image_dsc_t flappy_pipe_bot;
extern const lv_image_dsc_t flappy_ground;

