/* Auto-generated by scripts/flappy_assets_to_c.py — do not edit. */
#pragma once

#include <stddef.h>
#include <stdint.h>

typedef enum {
    FLAPPY_SFX_FLAP = 0,
    FLAPPY_SFX_SCORE,
    FLAPPY_SFX_DIE,
} flappy_sfx_id_t;

typedef struct {
    const uint8_t *data;
    size_t len;
    const char *name;
} flappy_sfx_blob_t;

extern const uint8_t flappy_sfx_flap[15032];
#define FLAPPY_SFX_FLAP_LEN 15032
extern const uint8_t flappy_sfx_score[15032];
#define FLAPPY_SFX_SCORE_LEN 15032
extern const uint8_t flappy_sfx_die[25064];
#define FLAPPY_SFX_DIE_LEN 25064

extern const flappy_sfx_blob_t flappy_sfx_table[3];

/* Minimal play hook. No ES8311 / I2S path in firmware yet (audio is
 * Planeado). Logs at DEBUG and returns ESP_ERR_NOT_SUPPORTED until
 * a real codec player exists. */
void flappy_sfx_play(flappy_sfx_id_t id);
